import { AppDatabase } from '../types';

export const initialDatabase: AppDatabase = {
  users: [
    {
      id: 'usr-coach-1',
      name: 'Coach Hendra Wijaya',
      email: 'coach.hendra@swimsport.id',
      role: 'coach',
      createdAt: '2026-01-10T08:00:00Z',
      updatedAt: '2026-01-10T08:00:00Z',
    },
    {
      id: 'usr-athlete-1',
      name: 'Bima Satria Wicaksana',
      email: 'bima.satria@swimsport.id',
      role: 'athlete',
      athleteId: 'ath-1',
      createdAt: '2026-01-15T08:00:00Z',
      updatedAt: '2026-01-15T08:00:00Z',
    },
    {
      id: 'usr-athlete-2',
      name: 'Alya Putri Rahmadani',
      email: 'alya.putri@swimsport.id',
      role: 'athlete',
      athleteId: 'ath-2',
      createdAt: '2026-01-15T08:00:00Z',
      updatedAt: '2026-01-15T08:00:00Z',
    },
  ],
  athletes: [
    {
      id: 'ath-1',
      namaLengkap: 'Bima Satria Wicaksana',
      namaPanggilan: 'Bima',
      jenisKelamin: 'L',
      tanggalLahir: '2011-04-18',
      kelompokUsia: 'KU II (14-15 th)',
      klub: 'Tirta Kencana SC',
      pelatih: 'Coach Hendra Wijaya',
      tanggalMulaiLatihan: '2020-03-01',
      tinggiBadan: 172,
      beratBadan: 63,
      nomorUtama: '50 m Freestyle',
      nomorTambahan: '100 m Freestyle, 50 m Butterfly',
      gayaUtama: 'Freestyle',
      gayaTambahan: ['Butterfly', 'Backstroke'],
      catatanKhusus: 'Fokus pada transisi breakout 15 meter pertama dan konsistensi stroke rate akhir.',
      avatarColor: 'from-cyan-500 to-blue-600',
      createdAt: '2026-01-15T08:00:00Z',
      updatedAt: '2026-09-20T08:00:00Z',
    },
    {
      id: 'ath-2',
      namaLengkap: 'Alya Putri Rahmadani',
      namaPanggilan: 'Alya',
      jenisKelamin: 'P',
      tanggalLahir: '2013-08-22',
      kelompokUsia: 'KU III (12-13 th)',
      klub: 'Tirta Kencana SC',
      pelatih: 'Coach Hendra Wijaya',
      tanggalMulaiLatihan: '2021-06-15',
      tinggiBadan: 160,
      beratBadan: 50,
      nomorUtama: '50 m Breaststroke',
      nomorTambahan: '100 m Breaststroke, 200 m IM',
      gayaUtama: 'Breaststroke',
      gayaTambahan: ['Individual Medley', 'Freestyle'],
      catatanKhusus: 'Kekuatan dorongan kaki katak (whip kick) sangat baik, perbaiki sudut elevasi kepala saat ambil nafas.',
      avatarColor: 'from-emerald-500 to-teal-600',
      createdAt: '2026-01-15T08:00:00Z',
      updatedAt: '2026-09-20T08:00:00Z',
    },
    {
      id: 'ath-3',
      namaLengkap: 'Kevin Pratama',
      namaPanggilan: 'Kevin',
      jenisKelamin: 'L',
      tanggalLahir: '2015-02-10',
      kelompokUsia: 'KU IV (10-11 th)',
      klub: 'Tirta Kencana SC',
      pelatih: 'Coach Hendra Wijaya',
      tanggalMulaiLatihan: '2022-01-10',
      tinggiBadan: 148,
      beratBadan: 40,
      nomorUtama: '50 m Backstroke',
      nomorTambahan: '50 m Freestyle',
      gayaUtama: 'Backstroke',
      gayaTambahan: ['Freestyle'],
      catatanKhusus: 'Anak memiliki motivasi tinggi, perlu kontrol rotasi pinggul agar jalur renang tetap lurus.',
      avatarColor: 'from-amber-500 to-orange-600',
      createdAt: '2026-02-01T08:00:00Z',
      updatedAt: '2026-09-20T08:00:00Z',
    },
  ],
  swim_results: [
    // Bima's 50m Freestyle Progression
    {
      id: 'sr-1',
      athleteId: 'ath-1',
      tanggal: '2026-06-12',
      jenisTes: 'Latihan',
      jarak: '50 m',
      gaya: 'Freestyle',
      waktu: '28.10',
      waktuDetik: 28.10,
      isPB: false,
      waktuSebelumnya: '28.50',
      selisihSebelumnya: -0.40,
      persentasePerubahan: -1.40,
      start: 'Diving standar, sedikit lambat respon',
      split: '25m: 13.60',
      strokeRate: 46,
      strokeCount: 33,
      catatanTeknik: 'Streamline awal bagus, nafas 2 kali di 15m terakhir',
      teknikKategori: ['Start', 'Breathing'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar',
      catatanPelatih: 'Fokus perbaiki reaksi start di blok.',
      createdAt: '2026-06-12T10:00:00Z',
      updatedAt: '2026-06-12T10:00:00Z',
    },
    {
      id: 'sr-2',
      athleteId: 'ath-1',
      tanggal: '2026-07-18',
      jenisTes: 'Time Trial',
      jarak: '50 m',
      gaya: 'Freestyle',
      waktu: '27.60',
      waktuDetik: 27.60,
      isPB: true,
      waktuSebelumnya: '28.10',
      selisihSebelumnya: -0.50,
      persentasePerubahan: -1.78,
      start: 'Reaksi 0.69s, breakout 12m',
      split: '25m: 13.20',
      strokeRate: 48,
      strokeCount: 32,
      catatanTeknik: 'Pacing di 25m pertama stabil',
      teknikKategori: ['Streamline', 'Pacing'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Sangat siap',
      catatanPelatih: 'Peningkatan signifikan pada efisiensi kayuhan.',
      createdAt: '2026-07-18T10:00:00Z',
      updatedAt: '2026-07-18T10:00:00Z',
    },
    {
      id: 'sr-3',
      athleteId: 'ath-1',
      tanggal: '2026-08-20',
      jenisTes: 'Evaluasi bulanan',
      jarak: '50 m',
      gaya: 'Freestyle',
      waktu: '27.10',
      waktuDetik: 27.10,
      isPB: true,
      waktuSebelumnya: '27.60',
      selisihSebelumnya: -0.50,
      persentasePerubahan: -1.81,
      start: 'Reaksi 0.66s, sudut masuk tajam',
      split: '25m: 12.95',
      strokeRate: 50,
      strokeCount: 31,
      catatanTeknik: 'Finish kuat tanpa mengangkat kepala terlalu awal',
      teknikKategori: ['Start', 'Finish'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar penuh',
      catatanPelatih: 'Kayuhan makin efisien (DPS meningkat).',
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-20T10:00:00Z',
    },
    {
      id: 'sr-4',
      athleteId: 'ath-1',
      tanggal: '2026-09-18',
      jenisTes: 'Kejuaraan',
      jarak: '50 m',
      gaya: 'Freestyle',
      waktu: '26.80',
      waktuDetik: 26.80,
      isPB: true,
      waktuSebelumnya: '27.10',
      selisihSebelumnya: -0.30,
      persentasePerubahan: -1.11,
      start: 'Reaksi 0.63s, dolphin kick underwater 6 kali',
      split: '25m: 12.70',
      strokeRate: 52,
      strokeCount: 30,
      catatanTeknik: 'Underwater kuat, kecepatan tinggi terjaga sampai sentuh dinding',
      teknikKategori: ['Underwater', 'Finish'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Peak performance',
      catatanPelatih: 'PB BARU! Breakout dan finish sangat rapi.',
      createdAt: '2026-09-18T10:00:00Z',
      updatedAt: '2026-09-18T10:00:00Z',
    },
    // Bima other strokes
    {
      id: 'sr-5',
      athleteId: 'ath-1',
      tanggal: '2026-09-10',
      jenisTes: 'Time Trial',
      jarak: '50 m',
      gaya: 'Butterfly',
      waktu: '28.90',
      waktuDetik: 28.90,
      isPB: true,
      waktuSebelumnya: '29.60',
      selisihSebelumnya: -0.70,
      persentasePerubahan: -2.36,
      start: 'Start eksplosif',
      split: '25m: 13.50',
      catatanTeknik: 'Timing nafas tiap 2 kayuhan',
      teknikKategori: ['Breathing', 'Stroke technique'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar',
      catatanPelatih: 'Recovery lengan lewat samping rapi.',
      createdAt: '2026-09-10T10:00:00Z',
      updatedAt: '2026-09-10T10:00:00Z',
    },
    {
      id: 'sr-6',
      athleteId: 'ath-1',
      tanggal: '2026-08-28',
      jenisTes: 'Time Trial',
      jarak: '50 m',
      gaya: 'Backstroke',
      waktu: '31.40',
      waktuDetik: 31.40,
      isPB: true,
      waktuSebelumnya: '32.10',
      selisihSebelumnya: -0.70,
      persentasePerubahan: -2.18,
      catatanTeknik: 'Rotasi bahu teratur',
      teknikKategori: ['Stroke technique'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar',
      createdAt: '2026-08-28T10:00:00Z',
      updatedAt: '2026-08-28T10:00:00Z',
    },
    {
      id: 'sr-7',
      athleteId: 'ath-1',
      tanggal: '2026-08-15',
      jenisTes: 'Time Trial',
      jarak: '50 m',
      gaya: 'Breaststroke',
      waktu: '36.50',
      waktuDetik: 36.50,
      isPB: true,
      waktuSebelumnya: '37.20',
      selisihSebelumnya: -0.70,
      persentasePerubahan: -1.88,
      catatanTeknik: 'Whip kick stabil',
      teknikKategori: ['Stroke technique'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar',
      createdAt: '2026-08-15T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    // Alya's Breaststroke
    {
      id: 'sr-8',
      athleteId: 'ath-2',
      tanggal: '2026-07-10',
      jenisTes: 'Latihan',
      jarak: '50 m',
      gaya: 'Breaststroke',
      waktu: '37.20',
      waktuDetik: 37.20,
      isPB: false,
      waktuSebelumnya: '37.80',
      selisihSebelumnya: -0.60,
      persentasePerubahan: -1.59,
      catatanTeknik: 'Glide 1 detik setiap kayuhan',
      teknikKategori: ['Streamline'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar',
      createdAt: '2026-07-10T10:00:00Z',
      updatedAt: '2026-07-10T10:00:00Z',
    },
    {
      id: 'sr-9',
      athleteId: 'ath-2',
      tanggal: '2026-08-14',
      jenisTes: 'Time Trial',
      jarak: '50 m',
      gaya: 'Breaststroke',
      waktu: '36.10',
      waktuDetik: 36.10,
      isPB: true,
      waktuSebelumnya: '37.20',
      selisihSebelumnya: -1.10,
      persentasePerubahan: -2.96,
      start: 'Diving stabil, breakout 10m',
      split: '25m: 17.10',
      strokeCount: 18,
      catatanTeknik: 'Underwater pullout optimal',
      teknikKategori: ['Underwater', 'Start'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Bugar',
      createdAt: '2026-08-14T10:00:00Z',
      updatedAt: '2026-08-14T10:00:00Z',
    },
    {
      id: 'sr-10',
      athleteId: 'ath-2',
      tanggal: '2026-09-15',
      jenisTes: 'Kejuaraan',
      jarak: '50 m',
      gaya: 'Breaststroke',
      waktu: '35.40',
      waktuDetik: 35.40,
      isPB: true,
      waktuSebelumnya: '36.10',
      selisihSebelumnya: -0.70,
      persentasePerubahan: -1.94,
      start: 'Reaksi 0.67s, pullout kuat',
      split: '25m: 16.80',
      strokeCount: 17,
      catatanTeknik: 'Timing tarikan dan tendangan menyatu halus',
      teknikKategori: ['Stroke technique', 'Finish'],
      kondisiKolam: '50m LCM',
      kondisiAtlet: 'Semangat tinggi',
      catatanPelatih: 'PB BARU! Posisi streamline saat glide sempurna.',
      createdAt: '2026-09-15T10:00:00Z',
      updatedAt: '2026-09-15T10:00:00Z',
    },
  ],
  training_logs: [
    {
      id: 'tl-1',
      athleteId: 'ath-1',
      tanggal: '2026-09-21',
      jenisLatihan: 'Renang',
      durasiMenit: 105,
      volumeMeter: 4200,
      rpe: 8,
      energiSebelum: 4,
      motivasiSebelum: 5,
      tidurSebelum: 4,
      energiSetelah: 3,
      kelelahanSetelah: 4,
      adaKeluhanNyeri: false,
      catatan: 'Main set 6x100m pace race target 58s. Ritme stabil.',
      createdAt: '2026-09-21T18:00:00Z',
      updatedAt: '2026-09-21T18:00:00Z',
    },
    {
      id: 'tl-2',
      athleteId: 'ath-1',
      tanggal: '2026-09-22',
      jenisLatihan: 'Fisik',
      durasiMenit: 60,
      volumeMeter: 0,
      rpe: 7,
      energiSebelum: 4,
      motivasiSebelum: 4,
      tidurSebelum: 4,
      energiSetelah: 3,
      kelelahanSetelah: 3,
      adaKeluhanNyeri: false,
      catatan: 'Dryland mobility bahu, core plank hold & dead bug.',
      createdAt: '2026-09-22T17:30:00Z',
      updatedAt: '2026-09-22T17:30:00Z',
    },
    {
      id: 'tl-3',
      athleteId: 'ath-1',
      tanggal: '2026-09-23',
      jenisLatihan: 'Renang',
      durasiMenit: 90,
      volumeMeter: 3600,
      rpe: 7,
      energiSebelum: 4,
      motivasiSebelum: 4,
      tidurSebelum: 4,
      energiSetelah: 3,
      kelelahanSetelah: 3,
      adaKeluhanNyeri: false,
      catatan: 'Aerobic base + drill catch-up freestyle.',
      createdAt: '2026-09-23T18:00:00Z',
      updatedAt: '2026-09-23T18:00:00Z',
    },
    {
      id: 'tl-4',
      athleteId: 'ath-1',
      tanggal: '2026-09-24',
      jenisLatihan: 'Recovery',
      durasiMenit: 45,
      volumeMeter: 1200,
      rpe: 4,
      energiSebelum: 3,
      motivasiSebelum: 4,
      tidurSebelum: 4,
      energiSetelah: 4,
      kelelahanSetelah: 2,
      adaKeluhanNyeri: false,
      catatan: 'Active recovery loose swim, peregangan dinamis, mandi kontras.',
      createdAt: '2026-09-24T17:00:00Z',
      updatedAt: '2026-09-24T17:00:00Z',
    },
    {
      id: 'tl-5',
      athleteId: 'ath-1',
      tanggal: '2026-09-25',
      jenisLatihan: 'Renang',
      durasiMenit: 100,
      volumeMeter: 3800,
      rpe: 8,
      energiSebelum: 5,
      motivasiSebelum: 5,
      tidurSebelum: 5,
      energiSetelah: 3,
      kelelahanSetelah: 4,
      adaKeluhanNyeri: false,
      catatan: 'Speed set 8x25m sprint max effort, start practice dari balok.',
      createdAt: '2026-09-25T18:00:00Z',
      updatedAt: '2026-09-25T18:00:00Z',
    },
  ],
  swim_programs: [
    {
      id: 'sp-1',
      athleteId: 'ath-1',
      namaProgram: 'Fase Development: Race Pace & Breakout Sprint',
      tanggal: '2026-09-26',
      fasePeriodisasi: 'Development',
      level: 'Kompetisi Remaja',
      pemanasan: '300m Choice swim santai + 4x50m Dinamis (25m Kick + 25m Drill) interval 1:15',
      teknikDrill: '4x50m Catch-up drill + 4x50m Fingertip drag (fokus rotasi tubuh dan high elbow catch)',
      mainSet: [
        {
          id: 'ms-1',
          rep: 4,
          jarak: 50,
          stroke: 'Freestyle (Race Pace Target: 27.5s)',
          interval: '1:30',
          rpe: 9,
          recovery: '30 detik aktif',
          note: 'Breakout underwater 12-15m tiap repetisi'
        },
        {
          id: 'ms-2',
          rep: 6,
          jarak: 25,
          stroke: 'Freestyle Max Sprint Dive',
          interval: '1:15',
          rpe: 10,
          recovery: '45 detik napas rileks',
          note: 'Fokus reaksi start cepat dan sentuhan dinding finish tajam'
        },
      ],
      speedSet: '4x15m Explosive breakout off the wall with fins',
      aerobicSet: '300m Pull buoy breathing alternate 3-5-7',
      coolDown: '200m Easy Choice (Backstroke / loose freestyle)',
      totalVolumeMeter: 3100,
      fokusProgram: 'Meningkatkan kecepatan akselerasi 25m pertama dan mempertahankan efisiensi kayuhan saat lelah.',
      disetujuiPelatih: true,
      createdAt: '2026-09-25T10:00:00Z',
      updatedAt: '2026-09-25T10:00:00Z',
    },
  ],
  physical_programs: [
    {
      id: 'pp-1',
      athleteId: 'ath-1',
      namaProgram: 'Dryland Atlet Renang: Core Stability & Shoulder Mobility',
      tanggal: '2026-09-26',
      fasePeriodisasi: 'Development',
      mobility: [
        'Shoulder CARs & band pass-through (2 set x 10 rep)',
        'Thoracic spine foam roller extension (3 menit)',
        'Ankle plantar flexion stretch (2 set x 30 detik)',
        'Hip 90/90 mobility rotation (2 set x 8 rep)'
      ],
      core: [
        'Front Plank hold (3 set x 45 detik)',
        'Side Plank with rotation (3 set x 30 detik/sisi)',
        'Dead Bug control (3 set x 12 rep lambat)',
        'Bird Dog with 3s isometric hold (3 set x 10 rep/sisi)'
      ],
      strength: [
        'Bodyweight Pull-ups / Inverted Row (3 set x 8 rep)',
        'Goblet Squat beban ringan (3 set x 10 rep)',
        'Push-up dengan tempo terkontrol (3 set x 12 rep)'
      ],
      power: [
        'Medicine Ball Chest Pass eksplosif (3 set x 6 rep) di bawah pantauan pelatih',
        'Broad Jump dengan pendaratan lembut (3 set x 5 rep)'
      ],
      coordination: [
        'Single-leg balance with tennis ball toss (2 set x 10 tangkapan/kaki)',
        'Agility ladder forward-backward quick feet'
      ],
      conditioning: [
        'Jump rope steady rhythm (3 x 2 menit, istirahat 1 menit)'
      ],
      catatanKeamanan: 'Bagi atlet KU II (14-15 tahun), hindari beban angkat berat di atas kepala. Selalu utamakan postur streamline, kontrol nafas teratur, dan hentikan jika ada nyeri pada sendi bahu.',
      disetujuiPelatih: true,
      createdAt: '2026-09-25T10:30:00Z',
      updatedAt: '2026-09-25T10:30:00Z',
    },
  ],
  targets: [
    {
      id: 'tgt-1',
      athleteId: 'ath-1',
      jarak: '50 m',
      gaya: 'Freestyle',
      pbSaatIni: '26.80',
      pbSaatIniDetik: 26.80,
      waktuTarget: '26.00',
      waktuTargetDetik: 26.00,
      selisihDetik: 0.80,
      targetJangka: '8 minggu',
      tanggalMulai: '2026-09-18',
      batasWaktu: '2026-11-13',
      status: 'In Progress',
      catatan: 'Sasaran Kejurda Jawa Timur 2026',
      createdAt: '2026-09-18T12:00:00Z',
      updatedAt: '2026-09-18T12:00:00Z',
    },
    {
      id: 'tgt-2',
      athleteId: 'ath-2',
      jarak: '50 m',
      gaya: 'Breaststroke',
      pbSaatIni: '35.40',
      pbSaatIniDetik: 35.40,
      waktuTarget: '34.50',
      waktuTargetDetik: 34.50,
      selisihDetik: 0.90,
      targetJangka: '12 minggu',
      tanggalMulai: '2026-09-15',
      batasWaktu: '2026-12-08',
      status: 'In Progress',
      catatan: 'Sasaran Kejuaraan Antar Klub Nasional',
      createdAt: '2026-09-15T12:00:00Z',
      updatedAt: '2026-09-15T12:00:00Z',
    },
  ],
  evaluations: [
    {
      id: 'ev-1',
      athleteId: 'ath-1',
      swimResultId: 'sr-4',
      tanggal: '2026-09-18',
      nomor: '50 m Freestyle',
      pb: '26.80',
      hasilTerbaru: '26.80',
      perubahanWaktu: '-0.30 detik',
      performaWaktu: 'lebih cepat',
      trenStatus: 'Tren Menanjak Positif (4 sesi berturut-turut mengalami perbaikan)',
      isPB: true,
      konsistensiStatus: 'Konsistensi Sangat Stabil (variasi waktu < 0.5s)',
      fokusBerikutnya: [
        'Optimasi daya dorong reaksi start pada blok',
        'Pertahankan efisiensi stroke rate 50-52 SPM di 15m terakhir',
        'Streamline breakout tanpa jeda transisi kayuhan pertama',
        'Finish agresif dengan kepala tetap terkunci di garis air'
      ],
      rekomendasiRenang: [
        'Drill breakout 15m eksplosif x 6 repetisi',
        'Short sprint 25m interval ketat @ 1:15',
        'Pace simulation 50m dengan pembagian 25m pertama dan kedua',
        'Latihan teknik touch finish menggunakan sentuhan ujung jari penuh'
      ],
      rekomendasiFisik: [
        'Penguatan core stability (plank variations & bird dog)',
        'Mobilitas sendi bahu dan ankle plantar flexion',
        'Latihan power lompatan eksplosif vertikal dan horizontal (bodyweight)',
        'Koordinasi kelincahan kaki'
      ],
      fokusPemulihan: [
        'Tidur malam berkualitas 8-9 jam untuk pemulihan jaringan otot',
        'Hidrasi teratur dan konsumsi karbohidrat-protein seimbang setelah latihan',
        'Active recovery renang santai 24 jam pasca sesi intensitas tinggi'
      ],
      catatanKeamanan: 'Jika atlet merasakan kelelahan berlebih atau ketegangan otot bahu yang tidak wajar, diskusikan segera dengan pelatih untuk penyesuaian volume latihan.',
      aiGenerated: false,
      createdAt: '2026-09-18T11:00:00Z',
      updatedAt: '2026-09-18T11:00:00Z',
    },
  ],
  recovery_logs: [
    {
      id: 'rl-1',
      athleteId: 'ath-1',
      tanggal: '2026-09-25',
      kualitasTidur: 5,
      jamTidur: 8.5,
      tingkatKelelahan: 3,
      tingkatStres: 2,
      nyeriOtot: 2,
      keluhanFisik: 'Tidak ada, otot terasa segar pasca istirahat.',
      bebanSekolahLain: 'Normal, tugas ringan.',
      catatan: 'Kondisi mental dan fisik siap untuk latihan speed set.',
      createdAt: '2026-09-25T07:00:00Z',
      updatedAt: '2026-09-25T07:00:00Z',
    },
  ],
};
